/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { WalletX, WalletXInterface } from "../WalletX.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_tokenAddress",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f5ffd5b5060405161018938038061018983398181016040528101906100319190610114565b805f5f6101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055503360015f6101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055505061013f565b5f5ffd5b5f73ffffffffffffffffffffffffffffffffffffffff82169050919050565b5f6100e3826100ba565b9050919050565b6100f3816100d9565b81146100fd575f5ffd5b50565b5f8151905061010e816100ea565b92915050565b5f60208284031215610129576101286100b6565b5b5f61013684828501610100565b91505092915050565b603e8061014b5f395ff3fe60806040525f5ffdfea26469706673582212200c4cfa32beea670b1d6ba07bc1a35bab6f512757b59e21929b25751780966d6d64736f6c634300081c0033";

  
      type WalletXConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: WalletXConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class WalletX__factory extends ContractFactory {
    
      constructor(...args: WalletXConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_tokenAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_tokenAddress, overrides || {});
    };
    override deploy(_tokenAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_tokenAddress, overrides || {}) as Promise<WalletX & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): WalletX__factory {
      return super.connect(runner) as WalletX__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): WalletXInterface {
      return new Interface(_abi) as WalletXInterface;
    }
    
    override attach(address: string | Addressable): WalletX {
      return super.attach(address) as WalletX;
    }
  static connect(address: string, runner?: ContractRunner | null): WalletX {
      return new Contract(address, _abi, runner) as unknown as WalletX;
    }
  }

  
  