/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { Error, ErrorInterface } from "../../../lib/errors.sol/Error.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InsufficientFunds",
    "type": "error"
  }
] as const;

  const _bytecode = "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212207ce09001b672c141364fe9a4d802a7c01756b8ee3613633c092ffd505390b85f64736f6c634300081c0033";

  
      type ErrorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: ErrorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Error__factory extends ContractFactory {
    
      constructor(...args: ErrorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Error & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Error__factory {
      return super.connect(runner) as Error__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): ErrorInterface {
      return new Interface(_abi) as ErrorInterface;
    }
    
    override attach(address: string | Addressable): Error {
      return super.attach(address) as Error;
    }
  static connect(address: string, runner?: ContractRunner | null): Error {
      return new Contract(address, _abi, runner) as unknown as Error;
    }
  }

  
  