/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WalletX } from './WalletX.js';
export * as factories from './factories/index.js';
export { WalletX__factory } from './factories/WalletX__factory.js';