/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20 } from './MockERC20.js';
export type { WalletX } from './WalletX.js';
export * as factories from './factories/index.js';
export { MockERC20__factory } from './factories/MockERC20__factory.js';
export { WalletX__factory } from './factories/WalletX__factory.js';