/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace WalletX {
      
    export type WalletMemberStruct = {memberAddress: AddressLike, adminAddress: AddressLike, organizationName: string, name: string, active: boolean, spendLimit: BigNumberish, memberIdentifier: BigNumberish, role: string}

    export type WalletMemberStructOutput = [memberAddress: string, adminAddress: string, organizationName: string, name: string, active: boolean, spendLimit: bigint, memberIdentifier: bigint, role: string] & {memberAddress: string, adminAddress: string, organizationName: string, name: string, active: boolean, spendLimit: bigint, memberIdentifier: bigint, role: string }
  

    export type MemberTransactionStruct = {amount: BigNumberish, reciever: AddressLike}

    export type MemberTransactionStructOutput = [amount: bigint, reciever: string] & {amount: bigint, reciever: string }
  

    export type WalletStruct = {adminAddress: AddressLike, walletName: string, active: boolean, walletId: BigNumberish, walletBalance: BigNumberish, role: string}

    export type WalletStructOutput = [adminAddress: string, walletName: string, active: boolean, walletId: bigint, walletBalance: bigint, role: string] & {adminAddress: string, walletName: string, active: boolean, walletId: bigint, walletBalance: bigint, role: string }
  
    }

  export interface WalletXInterface extends Interface {
    getFunction(nameOrSignature: "getAdminRole" | "getMember" | "getMemberTransactions" | "getMembers" | "getWalletAdmin" | "onboardMembers" | "registerWallet" | "reimburseMember" | "reimburseWallet"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getAdminRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMember', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMemberTransactions', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getMembers', values?: undefined): string;
encodeFunctionData(functionFragment: 'getWalletAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'onboardMembers', values: [AddressLike, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerWallet', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reimburseMember', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reimburseWallet', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getAdminRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMember', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMemberTransactions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMembers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWalletAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onboardMembers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reimburseMember', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reimburseWallet', data: BytesLike): Result;
  }

  

  export interface WalletX extends BaseContract {
    
    connect(runner?: ContractRunner | null): WalletX;
    waitForDeployment(): Promise<this>;

    interface: WalletXInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getAdminRole: TypedContractMethod<
      [_userAddress: AddressLike, ],
      [string],
      'view'
    >
    

    
    getMember: TypedContractMethod<
      [],
      [WalletX.WalletMemberStructOutput],
      'view'
    >
    

    
    getMemberTransactions: TypedContractMethod<
      [_memberAddress: AddressLike, ],
      [WalletX.MemberTransactionStructOutput[]],
      'view'
    >
    

    
    getMembers: TypedContractMethod<
      [],
      [WalletX.WalletMemberStructOutput[]],
      'view'
    >
    

    
    getWalletAdmin: TypedContractMethod<
      [],
      [WalletX.WalletStructOutput],
      'view'
    >
    

    
    onboardMembers: TypedContractMethod<
      [_memberAddress: AddressLike, _memberName: string, _fundAmount: BigNumberish, _memberIdentifier: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    registerWallet: TypedContractMethod<
      [_walletName: string, _fundAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reimburseMember: TypedContractMethod<
      [_memberIdentifier: BigNumberish, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reimburseWallet: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getAdminRole'): TypedContractMethod<
      [_userAddress: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMember'): TypedContractMethod<
      [],
      [WalletX.WalletMemberStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMemberTransactions'): TypedContractMethod<
      [_memberAddress: AddressLike, ],
      [WalletX.MemberTransactionStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getMembers'): TypedContractMethod<
      [],
      [WalletX.WalletMemberStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getWalletAdmin'): TypedContractMethod<
      [],
      [WalletX.WalletStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'onboardMembers'): TypedContractMethod<
      [_memberAddress: AddressLike, _memberName: string, _fundAmount: BigNumberish, _memberIdentifier: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerWallet'): TypedContractMethod<
      [_walletName: string, _fundAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reimburseMember'): TypedContractMethod<
      [_memberIdentifier: BigNumberish, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reimburseWallet'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }