/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace WalletX {
      
    export type WalletStruct = {adminAddress: AddressLike, walletName: string, active: boolean, walletId: BigNumberish, walletBalance: BigNumberish, role: string}

    export type WalletStructOutput = [adminAddress: string, walletName: string, active: boolean, walletId: bigint, walletBalance: bigint, role: string] & {adminAddress: string, walletName: string, active: boolean, walletId: bigint, walletBalance: bigint, role: string }
  
    }

  export interface WalletXInterface extends Interface {
    getFunction(nameOrSignature: "getWalletAdmin" | "registerWallet"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getWalletAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerWallet', values: [string, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getWalletAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerWallet', data: BytesLike): Result;
  }

  

  export interface WalletX extends BaseContract {
    
    connect(runner?: ContractRunner | null): WalletX;
    waitForDeployment(): Promise<this>;

    interface: WalletXInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getWalletAdmin: TypedContractMethod<
      [],
      [WalletX.WalletStructOutput],
      'view'
    >
    

    
    registerWallet: TypedContractMethod<
      [_walletName: string, _fundAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getWalletAdmin'): TypedContractMethod<
      [],
      [WalletX.WalletStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'registerWallet'): TypedContractMethod<
      [_walletName: string, _fundAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }